### ISSUE TITLE
make: *** No rule to make target `install'.  Stop.

### ISSUE THREAD

**Issue by manuelwallrapp** [operator-framework/java-operator-plugins#101]
Hi 

if I do:
`go mod tidy`
`make install`

I get a:
make: *** No rule to make target `install'.  Stop.

there is no target install in the Makefile. I execute it on Mac Os X with Go version 1.18. What am I doing wrong?

**Comment by laxmikantbpandhare** [comment]
@manuelwallrapp - Those steps are mentioned for the installation of `operator-sdk`. Please refer below link for the same - https://sdk.operatorframework.io/docs/installation/#prerequisites-1

**Comment by manuelwallrapp** [comment]
@laxmikantbpandhare  thank you for your answer. On your mentioned page it has prequisites operator-sdk v1.8, but v1.23 is the newest. If I execute:

operator-sdk create api --plugins quarkus --group cache --version v1 --kind Memcached                                                       

I get: 
FATA[0000] no plugin could be resolved with key "quarkus" for project version "3-alpha" 

So how do I get the quarkus plugin into the operator-sdk?

**Comment by laxmikantbpandhare** [comment]
@manuelwallrapp Could you please share what command you are using during initialization `init` also if possible could you please share generated `PROJECT` file here.

**Comment by manuelwallrapp** [comment]
I made a mistake, thanks for your help. I think all the different guides are a bit irritating. Once with the right guide it works.

**Comment by laxmikantbpandhare** [comment]
That's great. I am closing this issue as issue got resolved.
