### ISSUE TITLE
mvn install - incorrect schema in generated CRD under /target/kubernetes

### ISSUE THREAD

**Issue by tlwu2013** [operator-framework/java-operator-plugins#28]
#### What did you do?

Follow the [tutorial](https://github.com/operator-framework/java-operator-plugins/blob/main/docs/tutorial.md#via-quarkus-extension) to generate CRD with `mvn install` .

#### What did you expect to see?

The generated `memcacheds.cache.example.com-v1.yml` under `/target/kubernetes` should include a schema as specified in `MemcachedSpec.java` and `MemcachedStatus.java` as the one under `/target/classes/META-INF/fabric8`:
<img width="462" alt="ok_schema" src="https://user-images.githubusercontent.com/5903705/125718861-6dc9ed39-8709-4985-919f-3a3a1d066430.png">

#### What did you see instead? Under which circumstances?

The generated `memcacheds.cache.example.com-v1.yml` under `/target/kubernetes` only includes an empty object property as:
<img width="463" alt="ng_schema" src="https://user-images.githubusercontent.com/5903705/125718876-376ac642-3832-4452-b813-a47192946994.png">

#### Environment

**Operator type:**

/language java

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version: "v1.8.0-1-gc7401c73", commit: "c7401c73bb1dec39da8020d3702597342dc0dfc2", kubernetes version: "v1.20.2", go version: "go1.15.5", GOOS: "darwin", GOARCH: "amd64"`

`$ java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)`

`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-rc.0+120883f", GitCommit:"120883fe7ff642c7de79ec1e533e4c63cf099eb0", GitTreeState:"clean", BuildDate:"2021-06-12T07:15:42Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by jmrodri** [comment]
I verified this it is now generated properly.
