### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by metacosm** [operator-framework/java-operator-plugins#30]
## Type of question

Open question

## Question
When will this project be released? What will be the release frequency?

**Comment by laxmikantbpandhare** [comment]
> ## Type of question
> Open question
> 
> ## Question
> When will this project be released? What will be the release frequency?

This project is already releases. We release it with [operator-sdk releases](https://github.com/operator-framework/operator-sdk/releases). We do it every 3 weeks.

**Comment by metacosm** [comment]
There is no release of this project. The version used in operator sdk is referenced via a commit id in go.mod which makes it complex to figure out which version of the plug-in is used in a given operator sdk release.

**Comment by laxmikantbpandhare** [comment]
As part of this [PR](https://github.com/operator-framework/operator-sdk/pull/4871), we integrated java-plugin with Operator SDK and released in v1.8.0 Wee are able to scaffold out java-operator-plugin files using Operator SDK. Yes, it is difficult to see which version of plug-in is released. Maybe @jmrodri can help on this more.

**Comment by metacosm** [comment]
The whole point of this question is about having released versions that can be referenced for this plugin. I very well know that the plug-in is bundled in the operator sdk. That's not the question.

**Comment by laxmikantbpandhare** [comment]
okay. I got your point. Need to have released versions for this plugin.

**Comment by jmrodri** [comment]
So what I was thinking is the following:

**Comment by metacosm** [comment]
@jmrodri whatever works as long as we have something more easily referenceable 😉 
+1 on semver
