### ISSUE TITLE
Even without an `Operator` class being generated, the enclosing directory should be generated

### ISSUE THREAD

**Issue by metacosm** [operator-framework/java-operator-plugins#32]
#### Describe the problem you need a feature to resolve.

#31 removed the generation of the main class because the latest versions of the Quarkus extension don't require it. However, in the process of testing I found an issue with Quarkus: https://github.com/quarkusio/quarkus/issues/19655. An easy fix would be to still create an empty `src/main/java` directory.

#### Describe the solution you'd like.

`operator-sdk init` should generate an empty `src/main/java` directory. Not sure how to do it with the plugin.

**Comment by jmrodri** [comment]
Here's what it looks like immediately after init.

```
[jesusr@transam java-op]$ operator-sdk init --plugins quarkus  --domain zeusville.com --project-name java-op
[jesusr@transam java-op]$ tree
.
├── Makefile
├── pom.xml
├── PROJECT
└── src
    └── main
        ├── java
        └── resources
            └── application.properties

4 directories, 4 files
```

So where does a user START with this project now? Feels like I need to direct them a bit more now that there's no "main" :)

**Comment by metacosm** [comment]
Just create an API… without a controller, nothing happens anyway.

**Comment by jmrodri** [comment]
@metacosm @laxmikantbpandhare I added some instructions to the post scaffold similar to what we do in the ansible plugin. This will help guide folks to add the api. Thanks for the clarification.

**Comment by metacosm** [comment]
Thank you!
